device: cuda
guidance_scale: 7.5
image_path: C:/Tesis/imagic-editing.github.io/tedbench/originals/bird-g83440b9c4_1920.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: realistic
output_path: PNP-results/bird-g83440b9c4_1920_50
pnp_attn_t: 0.5
pnp_f_t: 0.8
prompt: Two kissing parrots.
sd_version: '2.1'
seed: 1
