device: cuda
guidance_scale: 7.5
image_path: C:/Tesis/imagic-editing.github.io/tedbench/originals/black_shirt.jpeg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: realistic
output_path: PNP-results/black_shirt_50
pnp_attn_t: 0.5
pnp_f_t: 0.8
prompt: A person giving a thumbs up.
sd_version: '2.1'
seed: 1
