device: cuda
guidance_scale: 7.5
image_path: C:/Tesis/imagic-editing.github.io/tedbench/originals/goat_and_cat.jpg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: realistic
output_path: PNP-results/goat_and_cat_50
pnp_attn_t: 0.5
pnp_f_t: 0.8
prompt: A goat to the right of a cat.
sd_version: '2.1'
seed: 1
