device: cuda
guidance_scale: 7.5
image_path: C:/Tesis/imagic-editing.github.io/tedbench/originals/milk_cookie.jpeg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: realistic
output_path: PNP-results/milk_cookie_50
pnp_attn_t: 0.5
pnp_f_t: 0.8
prompt: A cookie next to a glass of juice.
sd_version: '2.1'
seed: 1
