device: cuda
guidance_scale: 7.5
image_path: C:/Tesis/imagic-editing.github.io/tedbench/originals/vase_01.jpeg
latents_path: latents_forward
n_timesteps: 50
negative_prompt: realistic
output_path: PNP-results/vase_01_50
pnp_attn_t: 0.5
pnp_f_t: 0.8
prompt: A vase of flowers filled with green water.
sd_version: '2.1'
seed: 1
